# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 525)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 170, 741, 341))
        self.widget.setStyleSheet("background-color:#19647E;")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setObjectName("label_3")
        self.messagetxt = QtWidgets.QTextEdit(self.widget)
        self.messagetxt.setGeometry(QtCore.QRect(20, 80, 691, 181))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.messagetxt.setFont(font)
        self.messagetxt.setStyleSheet("Background-color:white;")
        self.messagetxt.setObjectName("messagetxt")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(620, 280, 89, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("Background-color:#F4D35E;")
        self.pushButton.setObjectName("pushButton")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 741, 151))
        self.widget_2.setStyleSheet("background-color:#28AFB0;")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(440, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.send_totxt = QtWidgets.QTextEdit(self.widget_2)
        self.send_totxt.setGeometry(QtCore.QRect(20, 70, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.send_totxt.setFont(font)
        self.send_totxt.setStyleSheet("Background-color:white;")
        self.send_totxt.setObjectName("send_totxt")
        self.subject_totxt = QtWidgets.QTextEdit(self.widget_2)
        self.subject_totxt.setGeometry(QtCore.QRect(440, 70, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.subject_totxt.setFont(font)
        self.subject_totxt.setStyleSheet("Background-color:white;")
        self.subject_totxt.setObjectName("subject_totxt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Message:"))
        self.pushButton.setText(_translate("Form", "SEND"))
        self.label.setText(_translate("Form", "To:"))
        self.label_2.setText(_translate("Form", "Subject:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
